/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CommentContainer.java
 *
 * Created on 13/08/2009, 09:34:59 AM
 */

package view;

import java.awt.BorderLayout;
import java.awt.GridLayout;

/**
 *
 * @author INTAPSA
 */
public class CommentContainer extends javax.swing.JPanel {

    /** Creates new form CommentContainer */
    public CommentContainer(int lines) {
        
        initComponents();
        setLayout(new GridLayout(lines, 1));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
