/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreateEnterprise.java
 *
 * Created on 3/08/2009, 12:18:35 PM
 */

package view;

import control.Consultas;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTextField;
import model.Ciudad;
import model.InfoEmpresa;
import model.InfoTipoContacto;
import resources.Cargador;


/**
 *
 * @author INTAPSA
 */
public class CreateEnterprise extends javax.swing.JFrame {

    private MainWindow mw;

    private ArrayList<InfoTipoContacto> tipos;
    private Consultas con;
    private String lastStringIfIsCreating;
    private ArrayList<Ciudad> ciudades;
    private boolean isEditing;
    private InfoEmpresa empresa;
    private boolean isProveedor;
    private int pkProvider;

    /** Creates new form CreateEnterprise */
    public CreateEnterprise(MainWindow mw, boolean isEditing, InfoEmpresa empresa) {
        initComponents();
        pkProvider = -1;
        con =mw.getB().getCon();
        proveedoresCombo.setModel(new DefaultComboBoxModel(con.getProveedores().toArray()));
        updateCiudades();
        this.empresa = empresa;
        this.isEditing = isEditing;
        this.mw =mw;
        lastStringIfIsCreating = new String();
        this.tipos =mw.getTipos();
       
          //Se carga Logo INTAP
         URL logo;
         logo = Cargador.imageURL("INTAPLOGO.JPG");

         if(logo != null){

             setIconImage(Toolkit.getDefaultToolkit().getImage(logo));
         }
       
        tiposBox.setModel(new DefaultComboBoxModel(tipos.toArray()));
        tiposBox.setSelectedItem(tipos.get(tipos.size()-1));
        if(isEditing){
            ciudadesBox.setSelectedItem((empresa.getCiudad()== null?new String():empresa.getCiudad()));
            tiposBox.setSelectedItem(getTipo(empresa.getTipoContacto()));
            nombreT.setText((empresa.getNombre()==null ? new String():empresa.getNombre()));
            nitT.setText((empresa.getNit()==null?new String():empresa.getNit()));
            indicativo.setText((empresa.getIndicativo()==null?new String():empresa.getIndicativo()));
            telT.setText((empresa.getTelefono()==null?new String():empresa.getTelefono()));
            ind_aux.setText((empresa.getIndicativo_aux()) ==null?new String():empresa.getIndicativo_aux());
            telefono_aux.setText((empresa.getTelefono_aux()==null?new String():empresa.getTelefono_aux()));
            FaxT.setText((empresa.getFax()==null?new String():empresa.getFax()));
            dirT.setText((empresa.getDireccion()==null?new String():empresa.getDireccion()));
            mailT.setText((empresa.getMail()==null?new String():empresa.getMail()));
        }else{

            empresa = new InfoEmpresa();

        }
        setLocationRelativeTo(null);
        setVisible(true);

    }

    private InfoTipoContacto getTipo(String nombre){
        for(InfoTipoContacto tipo :tipos){
            if(tipo.getDetalle().equals(nombre)){
                return tipo;
            }
        }
        return null;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tiposBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombreT = new javax.swing.JTextField();
        telT = new javax.swing.JTextField();
        nitT = new javax.swing.JTextField();
        dirT = new javax.swing.JTextField();
        nomM = new javax.swing.JLabel();
        nitM = new javax.swing.JLabel();
        telM = new javax.swing.JLabel();
        dirM = new javax.swing.JLabel();
        tipoM = new javax.swing.JLabel();
        indicativo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        telefono_aux = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ciudadesBox = new javax.swing.JComboBox();
        ind_aux = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        FaxT = new javax.swing.JTextField();
        proveedorL = new javax.swing.JLabel();
        proveedoresCombo = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        mailT = new javax.swing.JTextField();
        mailM = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion empresas");

        container.setBorder(javax.swing.BorderFactory.createMatteBorder(30, 30, 30, 30, new java.awt.Color(204, 204, 204)));
        container.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Empresa", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        save.setFont(new java.awt.Font("Tahoma", 1, 11));
        save.setText("Guardar");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save);

        cancel.setFont(new java.awt.Font("Tahoma", 1, 11));
        cancel.setText("Cancelar");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setText("Tipo contacto:");

        tiposBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tiposBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiposBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Nit:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Dirección:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Teléfono:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("Nombre:");

        //nombreT.setDocument(new JustLettersAndLenght(100));
        nombreT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreTFocusLost(evt);
            }
        });

        //telT.setDocument(new JustNumberAndLenght(7));
        telT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                telTFocusLost(evt);
            }
        });

        //nitT.setDocument(new JustNumberAndLenght(15));
        nitT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nitTFocusLost(evt);
            }
        });

        //dirT.setDocument(new LettersNumbersSpecialCharacterAndLength(200));
        dirT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dirTFocusLost(evt);
            }
        });

        nomM.setForeground(new java.awt.Color(255, 0, 0));
        nomM.setText("*");

        nitM.setForeground(new java.awt.Color(255, 0, 0));
        nitM.setText("*");

        telM.setForeground(new java.awt.Color(255, 0, 0));
        telM.setText("*");

        dirM.setForeground(new java.awt.Color(255, 0, 0));
        dirM.setText("*");

        tipoM.setForeground(new java.awt.Color(255, 0, 0));
        tipoM.setText("*");

        //indicativo.setDocument(new JustNumberAndLenght(4));
        indicativo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                indicativoFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText("Teléfono auxiliar:");

        //telefono_aux.setDocument(new JustNumberAndLenght(7));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel7.setText("Ciudad:");

        ciudadesBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Medellín", "Bogotá", "Cali", "Cartagena", "Añadir..." }));
        ciudadesBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadesBoxActionPerformed(evt);
            }
        });

        //ind_aux.setDocument(new JustNumberAndLenght(4));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel8.setText("Fax:");

        //FaxT.setDocument(new JustNumberAndLenght(10));

        proveedorL.setVisible(false);
        proveedorL.setFont(new java.awt.Font("Tahoma", 1, 11));
        proveedorL.setText("Proveedor:");

        proveedoresCombo.setVisible(false);
        proveedoresCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        proveedoresCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedoresComboActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Mail:");

        mailT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mailTFocusLost(evt);
            }
        });

        mailM.setForeground(new java.awt.Color(255, 0, 0));
        mailM.setText("*");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(46, 46, 46)
                            .addComponent(dirT, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(dirM))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(proveedorL)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(21, 21, 21)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tiposBox, 0, 224, Short.MAX_VALUE)
                                        .addComponent(ciudadesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(proveedoresCombo, 0, 224, Short.MAX_VALUE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(237, 237, 237)))
                            .addGap(4, 4, 4)
                            .addComponent(tipoM))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nitT, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                            .addComponent(nombreT, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(ind_aux)
                                                    .addComponent(indicativo, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(telefono_aux)
                                                    .addComponent(telT, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(75, 75, 75)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(FaxT, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(mailT, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(mailM)))))
                            .addGap(4, 4, 4)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(telM)
                                .addComponent(nitM)
                                .addComponent(nomM)))))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ciudadesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(tiposBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tipoM))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proveedorL)
                    .addComponent(proveedoresCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nombreT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nitT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nitM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(telT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(telM)
                        .addComponent(indicativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefono_aux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(ind_aux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(FaxT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(mailT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mailM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dirT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(dirM))
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        container.add(jPanel2, java.awt.BorderLayout.LINE_END);

        getContentPane().add(container, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        con.existsNit(nitT.getText().trim());

        if(check()){
            InfoTipoContacto tipo = (InfoTipoContacto)tiposBox.getSelectedItem();

            int pkTipo = tipo.getPK();
            String ciudad = String.valueOf(ciudadesBox.getSelectedItem());

                
            if(isEditing){
                if(!con.editarEmpresa(empresa.getId_empresa(), nitT.getText().trim(), dirT.getText().trim(), telT.getText().trim(),
                        nombreT.getText().trim(), telefono_aux.getText().trim(), indicativo.getText().trim(), ind_aux.getText().trim(), ciudad, FaxT.getText().trim(), mailT.getText().trim())){
                    JOptionPane.showMessageDialog(this, "Upss error al guardar, por favor inténtalo nuevamente.");
                }else{

                    empresa.setCiudad(ciudad);
                empresa.setDireccion(dirT.getText());
                empresa.setFax(FaxT.getText());
                empresa.setIndicativo(indicativo.getText());
                empresa.setIndicativo_aux(ind_aux.getText());
                empresa.setNit(nitT.getText());
                empresa.setNombre(nombreT.getText());
                empresa.setTelefono(telT.getText());
                empresa.setTelefono_aux(telefono_aux.getText());
                empresa.setMail(mailT.getText());

                dispose();
                }

                
            }else{
                if(con.insertEmpresa(nitT.getText().trim(), dirT.getText().trim(),
                        telT.getText().trim(), pkTipo, nombreT.getText().trim(),
                        ciudad, telefono_aux.getText().trim(), indicativo.getText().trim(), ind_aux.getText().trim(), FaxT.getText().trim(), String.valueOf(pkProvider), mailT.getText().trim())){
                    mw.updateEmpresasTipos();
                    dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "Upss, hubo un problema al guardar nueva empresa.  Inténtalo nuevamente.");
                }
            }
        }
}//GEN-LAST:event_saveActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void ciudadesBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadesBoxActionPerformed
        // TODO add your handling code here:
        String selectedItem = String.valueOf(ciudadesBox.getSelectedItem());
        if(selectedItem.equals("Añadir...")){
            final JPopupMenu newCity = new JPopupMenu("Nueva ciudad");
            final JTextField ciudad = new JTextField("Ciudad",40);
            ciudad.selectAll();
            final JTextField indi= new JTextField("Ind",3);
            indi.selectAll();


            ciudad.setText(lastStringIfIsCreating);
            JButton s = new JButton("Guardar");
            newCity.add(indi);
            newCity.add(ciudad);
            newCity.add(s);
            newCity.show(ciudadesBox, ciudadesBox.getX(), ciudadesBox.getY());
            s.addActionListener(new ActionListener() {

                public void actionPerformed(ActionEvent e) {
                   if(containsNumericChar(ciudad)){
                       JOptionPane.showMessageDialog(newCity, "¡EL nombre no debe contener caracteres numéricos!");
                       return;
                   }
                   if(ciudad.getText().isEmpty()){
                       JOptionPane.showMessageDialog(newCity, "¡Debe introducir un nombre válido!");
                       return;
                   }
                   if(indi.getText().isEmpty()){
                       JOptionPane.showMessageDialog(newCity, "¡Debe introducir un número válido!");
                   }
                   if(!onlyNumbers(indi)){
                       JOptionPane.showMessageDialog(newCity, "!Debe introducir un nombre válido!");
                   }
                   if(con.insertCiudad(ciudad.getText().trim(), Integer.valueOf(indi.getText().trim()))){
                       newCity.setVisible(false);
                       updateCiudades();
                       ciudadesBox.setSelectedItem(ciudad.getText().trim());
                       Ciudad c = new Ciudad();
                       c.setIndicativo(Integer.parseInt(indi.getText().trim()));
                       c.setNombre(ciudad.getText().trim());
                       indicativo.setText(String.valueOf(c.getIndicativo()));
                       ind_aux.setText(String.valueOf(c.getIndicativo()));

                       dispose();
                   }else{
                       JOptionPane.showMessageDialog(newCity, "¡Error al guardar.  Inténtalo nuevamente!");
                   }
                }
            });
        }else{

            Ciudad city = (Ciudad)ciudadesBox.getSelectedItem();
            indicativo.setText(String.valueOf(city.getIndicativo()));
            ind_aux.setText(String.valueOf(city.getIndicativo()));

        }

    }//GEN-LAST:event_ciudadesBoxActionPerformed

    private void nombreTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreTFocusLost
        // TODO add your handling code here:
        if(nombreT.getText().isEmpty()){
            nomM.setVisible(true);
        }else{
            nomM.setVisible(false);
        }
    }//GEN-LAST:event_nombreTFocusLost

    private void nitTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nitTFocusLost
        // TODO add your handling code here:
         if(nitT.getText().isEmpty()){
            nitM.setVisible(true);
        }else{
            nitM.setVisible(false);
        }
    }//GEN-LAST:event_nitTFocusLost

    private void indicativoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_indicativoFocusLost
        // TODO add your handling code here:
         if(indicativo.getText().isEmpty()){
            telM.setVisible(true);
        }else{
            telM.setVisible(false);
        }
    }//GEN-LAST:event_indicativoFocusLost

    private void telTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telTFocusLost
        // TODO add your handling code here:
           if(telT.getText().isEmpty()){
            telM.setVisible(true);
        }else{
            telM.setVisible(false);
        }
    }//GEN-LAST:event_telTFocusLost

    private void dirTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dirTFocusLost
        // TODO add your handling code here:
         if(dirT.getText().isEmpty()){
            dirM.setVisible(true);
        }else{
            dirM.setVisible(false);
        }
    }//GEN-LAST:event_dirTFocusLost

    private void tiposBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiposBoxActionPerformed
        // TODO add your handling code here:
        String selected = String.valueOf(tiposBox.getSelectedItem());
        if(selected.equals("--")){
            tipoM.setVisible(true);
        }else{
            tipoM.setVisible(false);
            if(selected.equals("Proveedores")){
                proveedorL.setVisible(true);
                proveedoresCombo.setVisible(true);
                InfoTipoContacto info = (InfoTipoContacto)proveedoresCombo.getSelectedItem();
                pkProvider = info.getPK();

            }else{
                 pkProvider = -1;
                 proveedorL.setVisible(false);
                 proveedoresCombo.setVisible(false);
            }
        }
    }//GEN-LAST:event_tiposBoxActionPerformed

    private void proveedoresComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedoresComboActionPerformed
        // TODO add your handling code here:
        InfoTipoContacto tipo = (InfoTipoContacto)proveedoresCombo.getSelectedItem();
        pkProvider = tipo.getPK();
    }//GEN-LAST:event_proveedoresComboActionPerformed

    private void mailTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailTFocusLost
        // TODO add your handling code here:
        if(!validateEmail(mailT.getText().trim())){
                    mailM.setVisible(true);
                }else{
                    mailM.setVisible(false);
                }
    }//GEN-LAST:event_mailTFocusLost


     private boolean validateEmail(String email){
             Pattern p = Pattern.compile("[a-zA-Z0-9]+[.[a-zA-Z0-9_-]+]*@[a-z0-9][\\w\\.-]*[a-z0-9]\\.[a-z][a-z\\.]*[a-z]$");//me gusta esta
            Matcher m = p.matcher(email);
        return m.matches();
    }
     private boolean containsNumericChar(JTextField text){
        char[] array = text.getText().toCharArray();
        for(int i=0;i<array.length;i++){
            if(isInteger(array[i])){
                return true;
            }
        }
        return false;
    }

    private boolean onlyNumbers(JTextField text){
        String t = text.getText().trim();
        try{
            Integer.parseInt(t);
            return true;
        }catch(NumberFormatException e){
            return false;
        }
    }

     private boolean isInteger(char a){
        try{
            Integer.parseInt(String.valueOf(a));
            return true;
        }catch(NumberFormatException e){
            return false;
        }
    }

     private boolean check(){
         nombreT.requestFocus();
         nitT.requestFocus();
         indicativo.requestFocus();
         telT.requestFocus();
         ind_aux.requestFocus();
         telefono_aux.requestFocus();
         FaxT.requestFocus();
         mailT.requestFocus();
         dirT.requestFocus();
         nombreT.requestFocus();
         if(tipoM.isVisible()||nomM.isVisible()||nitM.isVisible()||telM.isVisible()||
                 dirM.isVisible()|| mailM.isVisible()){
             return false;

         }
         return true;
     }



     private void updateCiudades(){

          ciudades = con.getCiudades();
          Ciudad c = new Ciudad();
          c.setNombre("Añadir...");
          ciudades.add(c);

         if(ciudades!= null){
             ciudadesBox.setModel(new DefaultComboBoxModel(ciudades.toArray()));
         }

     }

    /**
    * @param args the command line arguments
    */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FaxT;
    private javax.swing.JButton cancel;
    private javax.swing.JComboBox ciudadesBox;
    private javax.swing.JPanel container;
    private javax.swing.JLabel dirM;
    private javax.swing.JTextField dirT;
    private javax.swing.JTextField ind_aux;
    private javax.swing.JTextField indicativo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mailM;
    private javax.swing.JTextField mailT;
    private javax.swing.JLabel nitM;
    private javax.swing.JTextField nitT;
    private javax.swing.JLabel nomM;
    private javax.swing.JTextField nombreT;
    private javax.swing.JLabel proveedorL;
    private javax.swing.JComboBox proveedoresCombo;
    private javax.swing.JButton save;
    private javax.swing.JLabel telM;
    private javax.swing.JTextField telT;
    private javax.swing.JTextField telefono_aux;
    private javax.swing.JLabel tipoM;
    private javax.swing.JComboBox tiposBox;
    // End of variables declaration//GEN-END:variables

}


