/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreateEmpleado.java
 *
 * Created on 10/08/2009, 02:45:16 PM
 */

package view;

import com.toedter.calendar.JDateChooser;
import control.Consultas;
import java.awt.Toolkit;


import java.net.URL;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.StringTokenizer;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.Contacto;
import model.InfoEmpresa;

import resources.Cargador;
import utilities.JustLettersAndLenght;
import utilities.JustNumberAndLenght;
import utilities.LettersNumbersAndLenght;
import utilities.LettersNumbersSpecialCharacterAndLength;

/**
 *
 * @author INTAPSA
 */
public class CreateEmpleado extends javax.swing.JFrame {

    private MainWindow mw;
   
    private Consultas con;
   // private ArrayList<String> empString ;
    private ArrayList<Integer> empInteger;
    private Contacto info;
    private boolean isEditing;
    private JDateChooser ingreso;
    private JDateChooser nacimiento;
    /** Creates new form CreateEmpleado */
    public CreateEmpleado(MainWindow mw , boolean isEditing, Contacto info) {
        initComponents();
        this.mw = mw;
        this.isEditing = isEditing;
        con = mw.getB().getCon();
        this.info = info;
        if(info == null){
            info = new Contacto();
        }else{
            
            ubicacionT.setText(info.getNombreEmpresa());
            nombreT.setText(info.getNombreContacto());
            cedulaL.setText(info.getCedula());
            cargoL.setText(info.getCargo());
            formatIncomingDate(1, info.getFechaNacimiento());
            formatIncomingDate(2, info.getFechaIngreso());
            extensionT.setText(info.getExt());
            telefonoOfiT.setText(info.getTelefono());
            indPrincipalOfiT.setText(info.getIndicativo());
            indCasaT.setText(info.getIndicativo_casa());
            telefonoCasaT.setText(info.getTelefonoCasa());
            indCasaT1.setText(info.getIndicativo_casa());
            telefonoCasaT1.setText(info.getTelefonoCasa_aux());
            celularT.setText(info.getCelular());
            celAuxT.setText(info.getCelular_opcional());
            mailT.setText(info.getMail());
            direccionT.setText(info.getDireccion());
            barrioL.setText(info.getBarrio());
            observacionesT.setText(info.getObservaciones());
            opcionL.setText(info.getOpcion());
            
        }
        //Se carga Logo INTAP
        URL logo;
        logo = Cargador.imageURL("INTAPLOGO.JPG");

        if (logo != null) {

            setIconImage(Toolkit.getDefaultToolkit().getImage(logo));
        }
        setLocationRelativeTo(null);
        setTitle("Gestión Usuarios");
        setVisible(true);
    }

    private void formatIncomingDate(int option, String date){
        StringTokenizer st ;
        int año, mes ,dia;
        Calendar calendar = Calendar.getInstance();
        if(option==1){//nacimiento
            st = new StringTokenizer(date, "-");
            año = Integer.valueOf(st.nextToken());
            mes = Integer.valueOf(st.nextToken())-1;
            dia = Integer.valueOf(st.nextToken());
            calendar.set(año, mes, dia);
            nacimiento.setCalendar(calendar);
        }else if(option==2){//ingreso
            st = new StringTokenizer(date, "-");
            año = Integer.valueOf(st.nextToken());
            mes = Integer.valueOf(st.nextToken())-1;
            dia = Integer.valueOf(st.nextToken());
            calendar.set(año, mes, dia);
            ingreso.setCalendar(calendar);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        direccionT = new javax.swing.JTextField();
        celAuxT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observacionesT = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        save = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        nombreT = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        telefonoOfiT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        mailT = new javax.swing.JTextField();
        extensionT = new javax.swing.JTextField();
        celularT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        indCasaT = new javax.swing.JTextField();
        telefonoCasaT = new javax.swing.JTextField();
        indPrincipalOfiT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ubiM = new javax.swing.JLabel();
        nomM = new javax.swing.JLabel();
        dirM = new javax.swing.JLabel();
        telM = new javax.swing.JLabel();
        celM = new javax.swing.JLabel();
        mailM = new javax.swing.JLabel();
        dates = new javax.swing.JPanel();
        datesPanel = new javax.swing.JPanel();
        naciL = new javax.swing.JLabel();
        ingL = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        opcionL = new javax.swing.JTextField();
        telCasaM = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cedulaL = new javax.swing.JTextField();
        cedM = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        barrioL = new javax.swing.JTextField();
        barrioM = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cargoL = new javax.swing.JTextField();
        cargoM = new javax.swing.JLabel();
        telefonoCasaT1 = new javax.swing.JTextField();
        indCasaT1 = new javax.swing.JTextField();
        ubicacionT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        container1.setBorder(javax.swing.BorderFactory.createMatteBorder(30, 30, 30, 30, new java.awt.Color(204, 204, 204)));
        container1.setPreferredSize(new java.awt.Dimension(700, 730));
        container1.setVerifyInputWhenFocusTarget(false);
        container1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Empleado", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 700));
        jPanel2.setRequestFocusEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel8.setText("Observaciones:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("Ext:");

        //direccionT.setDocument(new LettersNumbersSpecialCharacterAndLength(200));
        direccionT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                direccionTFocusLost(evt);
            }
        });

        //celAuxT.setDocument(new JustNumberAndLenght(9));
        celAuxT.setColumns(10);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel10.setText("Ubicación:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Dirección:");

        observacionesT.setColumns(20);
        observacionesT.setLineWrap(true);
        observacionesT.setRows(5);
        observacionesT.setWrapStyleWord(true);
        jScrollPane1.setViewportView(observacionesT);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        save.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        save.setText("Guardar");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save);

        cancelar.setFont(new java.awt.Font("Tahoma", 1, 11));
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar);

        //nombreT.setDocument(new JustLettersAndLenght(100));
        nombreT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreTFocusLost(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel12.setText("Celular Auxiliar:");

        //telefonoOfiT.setDocument(new JustNumberAndLenght(6));
        telefonoOfiT.setColumns(7);
        telefonoOfiT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoOfiTActionPerformed(evt);
            }
        });
        telefonoOfiT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefonoOfiTFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Teléfono Oficina:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel11.setText("Teléfono casa:");

        //mailT.setDocument(new LettersNumbersSpecialCharacterAndLength(100));
        mailT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mailTFocusLost(evt);
            }
        });

        //extensionT.setDocument(new JustNumberAndLenght(3));
        extensionT.setColumns(4);
        extensionT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                extensionTFocusLost(evt);
            }
        });

        //celularT.setDocument(new JustNumberAndLenght(9));
        celularT.setColumns(10);
        celularT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                celularTFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText("Mail:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setText("Celular Principal:   ");

        //indCasaT.setDocument(new JustNumberAndLenght(2));
        indCasaT.setColumns(3);
        indCasaT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                indCasaTFocusLost(evt);
            }
        });

        //telefonoCasaT.setDocument(new JustNumberAndLenght(6));
        telefonoCasaT.setColumns(7);
        telefonoCasaT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefonoCasaTFocusLost(evt);
            }
        });

        //indPrincipalOfiT.setDocument(new JustNumberAndLenght(3));
        indPrincipalOfiT.setColumns(3);
        indPrincipalOfiT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                indPrincipalOfiTFocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Nombre:");

        ubiM.setVisible(false);
        ubiM.setFont(new java.awt.Font("Tahoma", 1, 11));
        ubiM.setForeground(new java.awt.Color(255, 0, 0));
        ubiM.setText("*");

        nomM.setVisible(false);
        nomM.setFont(new java.awt.Font("Tahoma", 1, 11));
        nomM.setForeground(new java.awt.Color(255, 0, 0));
        nomM.setText("*");

        dirM.setVisible(false);
        dirM.setFont(new java.awt.Font("Tahoma", 1, 11));
        dirM.setForeground(new java.awt.Color(255, 0, 0));
        dirM.setText("*");

        telM.setFont(new java.awt.Font("Tahoma", 1, 11));
        telM.setForeground(new java.awt.Color(255, 0, 0));
        telM.setText("*");
        telM.setVisible(false);

        celM.setFont(new java.awt.Font("Tahoma", 1, 11));
        celM.setForeground(new java.awt.Color(255, 0, 0));
        celM.setText("*");
        celM.setVisible(false);

        mailM.setFont(new java.awt.Font("Tahoma", 1, 11));
        mailM.setForeground(new java.awt.Color(255, 0, 0));
        mailM.setText("* Mail incorrecto");
        mailM.setVisible(false);

        datesPanel.setLayout(new java.awt.GridLayout(2, 0));
        nacimiento = new JDateChooser(new Date());
        ingreso = new JDateChooser(new Date());
        datesPanel.add(nacimiento);
        datesPanel.add(ingreso);

        naciL.setFont(new java.awt.Font("Tahoma", 1, 11));
        naciL.setText("Fecha Nacimiento:");

        ingL.setFont(new java.awt.Font("Tahoma", 1, 11));
        ingL.setText("Fecha Ingreso:");

        javax.swing.GroupLayout datesLayout = new javax.swing.GroupLayout(dates);
        dates.setLayout(datesLayout);
        datesLayout.setHorizontalGroup(
            datesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(naciL)
                    .addComponent(ingL))
                .addContainerGap(174, Short.MAX_VALUE))
            .addGroup(datesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datesLayout.createSequentialGroup()
                    .addContainerGap(128, Short.MAX_VALUE)
                    .addComponent(datesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        datesLayout.setVerticalGroup(
            datesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datesLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(naciL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingL)
                .addGap(19, 19, 19))
            .addGroup(datesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(datesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(datesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel16.setText("Opción:");

        //opcionL.setDocument(new JustNumberAndLenght(1));
        opcionL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                opcionLFocusLost(evt);
            }
        });

        telCasaM.setFont(new java.awt.Font("Tahoma", 1, 11));
        telCasaM.setForeground(new java.awt.Color(255, 0, 0));
        telCasaM.setText("*");
        telCasaM.setVisible(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel7.setText("Cédula:");

        //cedulaL.setDocument(new JustNumberAndLenght(11));
        cedulaL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cedulaLFocusLost(evt);
            }
        });

        cedM.setVisible(false);
        cedM.setFont(new java.awt.Font("Tahoma", 1, 11));
        cedM.setForeground(new java.awt.Color(255, 0, 0));
        cedM.setText("*");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel9.setText("Barrio:");

        //barrioL.setDocument(new LettersNumbersAndLenght(50));
        barrioL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                barrioLFocusLost(evt);
            }
        });

        barrioM.setVisible(false);
        barrioM.setFont(new java.awt.Font("Tahoma", 1, 11));
        barrioM.setForeground(new java.awt.Color(255, 0, 0));
        barrioM.setText("*");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel14.setText("Cargo:");

        //cargoL.setDocument(new JustLettersAndLenght(100));
        cargoL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cargoLFocusLost(evt);
            }
        });

        cargoM.setFont(new java.awt.Font("Tahoma", 1, 11));
        cargoM.setForeground(new java.awt.Color(255, 0, 0));
        cargoM.setText("*");
        cargoM.setVisible(false);

        //telefonoCasaT1.setDocument(new JustNumberAndLenght(6));
        telefonoCasaT1.setColumns(7);

        //indCasaT1.setDocument(new JustNumberAndLenght(2));
        indCasaT1.setColumns(3);

        //ubicacionT.setDocument(new JustLettersAndLenght(20));
        ubicacionT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ubicacionTFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(indCasaT)
                                .addComponent(indCasaT1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(indPrincipalOfiT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(telefonoCasaT1)
                            .addComponent(telefonoCasaT)
                            .addComponent(telefonoOfiT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(extensionT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(opcionL, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(telM, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(telCasaM, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ubicacionT, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ubiM))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreT, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(nomM))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cedulaL, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cedM))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cargoL, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cargoM)))
                        .addGap(91, 91, 91))
                    .addComponent(jLabel8)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(mailT, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mailM))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(celularT)
                                    .addComponent(celAuxT, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(celM))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(direccionT, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dirM))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(barrioL, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(barrioM)))
                                .addGap(46, 46, 46))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(305, 305, 305))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jLabel10)
                    .addComponent(ubicacionT, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ubiM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreT, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(nomM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(cedulaL, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cedM))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(jLabel14)
                            .addComponent(cargoM)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cargoL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telefonoOfiT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(extensionT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telM)
                            .addComponent(jLabel16)
                            .addComponent(opcionL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(indPrincipalOfiT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(indCasaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefonoCasaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(telCasaM)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(indCasaT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoCasaT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jLabel5)
                    .addComponent(celularT, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(celM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(celAuxT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(mailT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mailM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccionT, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(dirM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barrioL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(barrioM))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {barrioL, cargoL, cedulaL, celAuxT, celularT, direccionT, mailT, nombreT, ubicacionT});

        container1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(container1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void indPrincipalOfiTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_indPrincipalOfiTFocusLost
        // TODO add your handling code here:
        if(indPrincipalOfiT.getText().isEmpty()){
            telM.setVisible(true);

        }else{
            telM.setVisible(false);
        }
}//GEN-LAST:event_indPrincipalOfiTFocusLost

    private void telefonoCasaTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoCasaTFocusLost
        // TODO add your handling code here:

          if(telefonoCasaT.getText().isEmpty()){
            telCasaM.setVisible(true);

        }else{
            telCasaM.setVisible(false);
        }
}//GEN-LAST:event_telefonoCasaTFocusLost

    private void indCasaTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_indCasaTFocusLost
        // TODO add your handling code here:
        if(indCasaT.getText().isEmpty()){
            telCasaM.setVisible(true);

        }else{
            telCasaM.setVisible(false);
        }
}//GEN-LAST:event_indCasaTFocusLost

    private void celularTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_celularTFocusLost
        // TODO add your handling code here:
          if(celularT.getText().isEmpty()){
            celM.setVisible(true);

        }else{
            celM.setVisible(false);
        }
    }//GEN-LAST:event_celularTFocusLost

    private void mailTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailTFocusLost
        // TODO add your handling code here:
        if(mailT.getText().trim().isEmpty()){
            mailM.setVisible(true);

        }else{
            if(!validateEmail(mailT.getText().trim())){
                mailM.setVisible(true);
            }else{
                mailM.setVisible(false);
            }
        }
}//GEN-LAST:event_mailTFocusLost

    private void telefonoOfiTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoOfiTFocusLost
        // TODO add your handling code here:
        if(telefonoOfiT.getText().isEmpty()){
            telM.setVisible(true);

        }else{
            telM.setVisible(false);
        }
}//GEN-LAST:event_telefonoOfiTFocusLost

    private void telefonoOfiTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoOfiTActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_telefonoOfiTActionPerformed

    private void nombreTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreTFocusLost
        // TODO add your handling code here:
        if(nombreT.getText().isEmpty()){
            nomM.setVisible(true);
        }else{
            nomM.setVisible(false);
        }
    }//GEN-LAST:event_nombreTFocusLost

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_cancelarActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:


       String añoN, añoIng, mesN, mesIng, diaN, diaIng, dateIng, dateN;

       if(check()){
                    Calendar calendarNacimiento = Calendar.getInstance();
                    calendarNacimiento.setTime(nacimiento.getDate());
                    Calendar calendarIngreso = Calendar.getInstance();
                    calendarIngreso.setTime(ingreso.getDate());
                    añoIng = String.valueOf(calendarIngreso.get(Calendar.YEAR));
                    mesIng = String.valueOf(calendarIngreso.get(Calendar.MONTH)+1);
                    diaIng = String.valueOf(calendarIngreso.get(Calendar.DAY_OF_MONTH));

                    dateIng = añoIng+"-"+mesIng+"-"+diaIng;

                    añoN = String.valueOf(calendarNacimiento.get(Calendar.YEAR));
                    mesN = String.valueOf(calendarNacimiento.get(Calendar.MONTH)+1);
                    diaN = String.valueOf(calendarNacimiento.get(Calendar.DAY_OF_MONTH));

                    dateN = añoN+"-"+mesN+"-"+diaN;

                if(!isEditing){

                    info = new Contacto();
                    String opcion = opcionL.getText().trim();



                        if(con.insertEmpleado(nombreT.getText().trim(), cedulaL.getText().trim(),
                                ubicacionT.getText().trim(), telefonoOfiT.getText().trim(), extensionT.getText().trim(),
                                celularT.getText().trim(),  telefonoCasaT.getText().trim(),
                                dateN, dateIng, direccionT.getText().trim(), barrioL.getText().trim(),
                                opcionL.getText().trim(), celAuxT.getText().trim(), indPrincipalOfiT.getText().trim()
                                , indCasaT.getText().trim(), telefonoCasaT1.getText().trim(), indCasaT1.getText().trim(), mailT.getText().trim(), cargoL.getText().trim())){

                     info.setNombreContacto(nombreT.getText().trim());
                     info.setCedula(cedulaL.getText().trim());
                     info.setNombreEmpresa(ubicacionT.getText().trim());
                     info.setTelefono( telefonoOfiT.getText().trim());
                     info.setExt(extensionT.getText().trim());
                     info.setCelular(celularT.getText().trim());
                     info.setTelefonoCasa(telefonoCasaT.getText().trim());
                     info.setFechaIngreso(dateIng);
                     info.setFechaNacimiento(dateN);
                     info.setDireccion(direccionT.getText().trim());
                     info.setBarrio(barrioL.getText().trim());
                     info.setOpcion(opcionL.getText().trim());
                     info.setCelular_opcional(celAuxT.getText().trim());
                     info.setIndicativo(indPrincipalOfiT.getText().trim());
                     info.setIndicativo_casa(indCasaT.getText().trim());
                     info.setTelefonoCasa_aux(telefonoCasaT1.getText().trim());
                     info.setIndicativo_casa_aux(indCasaT1.getText().trim());
                     info.setMail(mailT.getText().trim());
                     info.setCargo(cargoL.getText().trim());
                     mw.updateEmpresasTipos();

                            dispose();
                        }else{
                            JOptionPane.showMessageDialog(this, "Upss error al guardar, por favor inténtalo nuevamente.");
                        }

                }else{
                    String opcion = opcionL.getText().trim();

                        if(con.editarEmpleado(nombreT.getText().trim(), cedulaL.getText().trim(),
                                ubicacionT.getText().trim(), telefonoOfiT.getText().trim(), extensionT.getText().trim(),
                                celularT.getText().trim(),  telefonoCasaT.getText().trim(),
                                dateN, dateIng, direccionT.getText().trim(), barrioL.getText().trim(),
                                opcionL.getText().trim(), celAuxT.getText().trim(), indPrincipalOfiT.getText().trim()
                                , indCasaT.getText().trim(), telefonoCasaT1.getText().trim(), indCasaT1.getText().trim(), mailT.getText().trim(),info.getPK() ,cargoL.getText().trim())){

                           info.setNombreContacto(nombreT.getText().trim());
                         info.setCedula(cedulaL.getText().trim());
                         info.setNombreEmpresa(ubicacionT.getText().trim());
                         info.setTelefono( telefonoOfiT.getText().trim());
                         info.setExt(extensionT.getText().trim());
                         info.setCelular(celularT.getText().trim());
                         info.setTelefonoCasa(telefonoCasaT.getText().trim());
                         info.setFechaIngreso(dateIng);
                         info.setFechaNacimiento(dateN);
                         info.setDireccion(direccionT.getText().trim());
                         info.setBarrio(barrioL.getText().trim());
                         info.setOpcion(opcionL.getText().trim());
                         info.setCelular_opcional(celAuxT.getText().trim());
                         info.setIndicativo(indPrincipalOfiT.getText().trim());
                         info.setIndicativo_casa(indCasaT.getText().trim());
                         info.setTelefonoCasa_aux(telefonoCasaT1.getText().trim());
                         info.setIndicativo_casa_aux(indCasaT1.getText().trim());
                         info.setMail(mailT.getText().trim());
                         info.setCargo(cargoL.getText().trim());
                         mw.updateEmpresasTipos();
                            dispose();
                        }else{
                            JOptionPane.showMessageDialog(this, "Upss error al guardar, por favor inténtalo nuevamente.");
                        }


                }
       }
}//GEN-LAST:event_saveActionPerformed



    private void direccionTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_direccionTFocusLost
        // TODO add your handling code here:
        if(direccionT.getText().trim().isEmpty()){
            dirM.setVisible(true);

        }else{

            dirM.setVisible(false);

        }
}//GEN-LAST:event_direccionTFocusLost

    private void ubicacionTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ubicacionTFocusLost
        // TODO add your handling code here:
        if(ubicacionT.getText().isEmpty()){
            ubiM.setVisible(true);
        }else{
            ubiM.setVisible(false);
        }
    }//GEN-LAST:event_ubicacionTFocusLost

    private void cedulaLFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cedulaLFocusLost
        // TODO add your handling code here:
        if(cedulaL.getText().isEmpty()){
            cedM.setVisible(true);

        }else{
            cedM.setVisible(false);
        }
    }//GEN-LAST:event_cedulaLFocusLost

    private void cargoLFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cargoLFocusLost
        // TODO add your handling code here:
        if(cargoL.getText().isEmpty()){
            cargoM.setVisible(true);

        }else{
            cargoM.setVisible(false);
        }
    }//GEN-LAST:event_cargoLFocusLost

    private void barrioLFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_barrioLFocusLost
        // TODO add your handling code here:
          if(barrioL.getText().isEmpty()){
            barrioM.setVisible(true);

        }else{
            barrioM.setVisible(false);
        }
    }//GEN-LAST:event_barrioLFocusLost

    private void extensionTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_extensionTFocusLost
        // TODO add your handling code here:
        if(extensionT.getText().trim().isEmpty()){
            if(opcionL.getText().trim().isEmpty()){
                telM.setVisible(true);
            }else{
                telM.setVisible(false);
            }
        }else{
            telM.setVisible(false);
        }
    }//GEN-LAST:event_extensionTFocusLost

    private void opcionLFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_opcionLFocusLost
        // TODO add your handling code here:
        if(opcionL.getText().trim().isEmpty()){
            if(extensionT.getText().trim().isEmpty()){
                telM.setVisible(true);
            }else{
                telM.setVisible(false);
            }
        }else{
            telM.setVisible(false);
        }
    }//GEN-LAST:event_opcionLFocusLost

    private boolean check(){

    if(ubicacionT.getText().isEmpty()){ //ubicacion
            ubiM.setVisible(true);
        }else{
            ubiM.setVisible(false);
        }

    if(nombreT.getText().isEmpty()){//Nombre
            nomM.setVisible(true);
        }else{
            nomM.setVisible(false);
        }

     if(cedulaL.getText().isEmpty()){//Cedula
            cedM.setVisible(true);

        }else{
            cedM.setVisible(false);
        }

    if(cargoL.getText().isEmpty()){//Cargo
            cargoM.setVisible(true);

        }else{
            cargoM.setVisible(false);
        }

    if(indPrincipalOfiT.getText().isEmpty()){//Indicativo oficina
            telM.setVisible(true);

        }else{
            telM.setVisible(false);
        }


     if(telefonoOfiT.getText().isEmpty()){//Telefono oficina
            telM.setVisible(true);

        }else{
            telM.setVisible(false);
        }

     if(extensionT.getText().trim().isEmpty()){//Extension oficina
            if(opcionL.getText().trim().isEmpty()){
                telM.setVisible(true);
            }else{
                telM.setVisible(false);
            }
        }else{
            telM.setVisible(false);
        }


     if(opcionL.getText().trim().isEmpty()){//Opcion oficina
            if(extensionT.getText().trim().isEmpty()){
                telM.setVisible(true);
            }else{
                telM.setVisible(false);
            }
        }else{
            telM.setVisible(false);
        }

    
     if(indCasaT.getText().isEmpty()){//Indicativo casa
            telCasaM.setVisible(true);

        }else{
            telCasaM.setVisible(false);
        }
    
        if(telefonoCasaT.getText().isEmpty()){//Telefono casa
            telCasaM.setVisible(true);

        }else{
            telCasaM.setVisible(false);
        }

      if(celularT.getText().isEmpty()){//celular
            celM.setVisible(true);

        }else{
            celM.setVisible(false);
        }

    if(mailT.getText().trim().isEmpty()){//mail
            mailM.setVisible(true);

        }else{
            if(!validateEmail(mailT.getText().trim())){
                mailM.setVisible(true);
            }else{
                mailM.setVisible(false);
            }
        }

     if(direccionT.getText().trim().isEmpty()){//Direcci0on
            dirM.setVisible(true);

        }else{

            dirM.setVisible(false);

        }

        if(barrioL.getText().isEmpty()){//Barrio
            barrioM.setVisible(true);

        }else{
            barrioM.setVisible(false);
        }



        if(ubiM.isVisible()){

            return false;
        }
        if(nomM.isVisible()){
            return false;
        }

        if(cedM.isVisible() ){
            return false;
        }
        if(cargoM.isVisible() ){
            return false;
        }
        if(telM.isVisible() ){
            return false;
        }

        if(telCasaM.isVisible() ){
            return false;
        }

         if(mailM.isVisible()){
            return false;
        }

        if( dirM.isVisible() ){
            return false;
        }


        if(  barrioM.isVisible() ){
            return false;
        }

            return true;
    }

    private boolean validateEmail(String email){
             Pattern p = Pattern.compile("[a-zA-Z0-9]+[.[a-zA-Z0-9_-]+]*@[a-z0-9][\\w\\.-]*[a-z0-9]\\.[a-z][a-z\\.]*[a-z]$");//me gusta esta
            Matcher m = p.matcher(email);
        return m.matches();
    }
    /**
    * @param args the command line arguments
    */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barrioL;
    private javax.swing.JLabel barrioM;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField cargoL;
    private javax.swing.JLabel cargoM;
    private javax.swing.JLabel cedM;
    private javax.swing.JTextField cedulaL;
    private javax.swing.JTextField celAuxT;
    private javax.swing.JLabel celM;
    private javax.swing.JTextField celularT;
    private javax.swing.JPanel container1;
    private javax.swing.JPanel dates;
    private javax.swing.JPanel datesPanel;
    private javax.swing.JLabel dirM;
    private javax.swing.JTextField direccionT;
    private javax.swing.JTextField extensionT;
    private javax.swing.JTextField indCasaT;
    private javax.swing.JTextField indCasaT1;
    private javax.swing.JTextField indPrincipalOfiT;
    private javax.swing.JLabel ingL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mailM;
    private javax.swing.JTextField mailT;
    private javax.swing.JLabel naciL;
    private javax.swing.JLabel nomM;
    private javax.swing.JTextField nombreT;
    private javax.swing.JTextArea observacionesT;
    private javax.swing.JTextField opcionL;
    private javax.swing.JButton save;
    private javax.swing.JLabel telCasaM;
    private javax.swing.JLabel telM;
    private javax.swing.JTextField telefonoCasaT;
    private javax.swing.JTextField telefonoCasaT1;
    private javax.swing.JTextField telefonoOfiT;
    private javax.swing.JLabel ubiM;
    private javax.swing.JTextField ubicacionT;
    // End of variables declaration//GEN-END:variables

}
