/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ShowType.java
 *
 * Created on 9/08/2009, 12:57:16 PM
 */

package view;

import control.ShowTypeControl;
import model.InfoTipoContacto;

/**
 *
 * @author INTAPSA
 */
public class ShowType extends javax.swing.JPanel {

    private MainWindow mw;
    private InfoTipoContacto tipo;
    private ShowTypeControl control;

    /** Creates new form ShowType */
    public ShowType(MainWindow mw, InfoTipoContacto tipo) {
        this.mw = mw;
        this.tipo = tipo;
        initComponents();
        control = new ShowTypeControl(this, mw, tipo);

        if(tipo.isIsProveedor()){
            tipoOProveedorL1.setText("Proveedor:");
            nombreL1.setText(tipo.getDetalle());

        }else{
            tipoOProveedorL1.setText("Tipo contacto:");
            nombreL1.setText(tipo.getDetalle());
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        tipoOProveedorL1 = new javax.swing.JLabel();
        nombreL1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4formMouseEntered(evt);
            }
        });
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.BorderLayout());
        jPanel5.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        tipoOProveedorL1.setFont(new java.awt.Font("Tahoma", 1, 11));
        tipoOProveedorL1.setText("Proveedor o Tipo Contacto:");

        nombreL1.setText("nombre");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tipoOProveedorL1)
                .addGap(18, 18, 18)
                .addComponent(nombreL1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoOProveedorL1)
                    .addComponent(nombreL1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel7, java.awt.BorderLayout.LINE_START);

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        add(jPanel4, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel4formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4formMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4formMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel nombreL1;
    private javax.swing.JLabel tipoOProveedorL1;
    // End of variables declaration//GEN-END:variables

}
